version: "3.2"
services:
  php:
    build:
      context: './php/'
      args:
       PHP_VERSION: 5.6
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: php
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: 2.4.32
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./public_html/:/var/www/html/
    container_name: apache

networks:
  frontend:
  backend:
volumes:
    data: